### ISSUE TITLE
Is the opposite possible as well?

### ISSUE THREAD

**Issue by SirWindfield** [rxaviers/relative-time#13]
I am currently looking for a library that allows me to convert relative strings like `24h` or `1d 12h` to datetimes relative to `now()`. Preferably stuff like `monday` would parse to the next monday from `now()`.

Is this possible with this library? If not, do you know any library that supports this?

**Comment by rxaviers** [comment]
Not possible with this library, whose purpose it to display/format a Date object into a localized string. You need a parser. Also note that `24h` and `1d 12h` aren't output you get using relative time. Those are output you get using a unit formatter (or a duration formatter).
