### ISSUE TITLE
Comparison with Luxon (from Moment.js)

### ISSUE THREAD

**Issue by rdhar** [rxaviers/relative-time#8]
This is more of a curiosity than an issue; how does this project differ from Luxon? In terms of features, functionality and scope of what each of them provide.

More specifically referring to Luxon's docs under [Output > Humanization](https://moment.github.io/luxon/docs/manual/moment.html#humanization), they use `Intl.RelativeTimeFormat` which also happens to be mentioned in the currently open PR #5. Would it be possible to append Luxon's output results to the comparison tables in [README.md](https://github.com/rxaviers/relative-time/blob/master/README.md)?

**Comment by rxaviers** [comment]
PR welcome
